directory: /app/library
library: /data/musiclibrary.db

plugins: fetchart

fetchart:
  auto: yes
  maxwidth: 1000
  sources: coverart itunes amazon

import:
  timid: no
  quiet_fallback: asis
  strong_rec_thresh: 0.10
  medium_rec_thresh: 0.25
  none_rec_action: asis
  medium_rec_action: asis
  incremental: yes
  quiet: yes
  autotag: yes
  write: yes
  move: yes
  copy: no

match:
  strong_rec_thresh: 0.10
  medium_rec_thresh: 0.25
  rec_gap_thresh: 0.25
  preferred:
    countries: ['US', 'GB', 'XW']
    media: ['Digital Media|File', 'CD']

paths:
  default: $albumartist/$album/$track $title
  singleton: $albumartist/$album/$track $title
